/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package offlinesignature;

import helpers.Accounts;
import helpers.Utility;
import helpers.algorithm.Compare;
import java.awt.Image;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Onuwa Nnachi Isaac <i_onuwa4u@outlook.com>
 */
public class Verification extends javax.swing.JFrame {

    /**
     * Creates new form Verification
     */
    public Verification() {
        initComponents();
        jVerifyingValue.setVisible(false);
        jEnrolledValue.setVisible(false);
        jAnalyze.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAccountNumber = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jVerifying = new javax.swing.JLabel();
        jEnrolled = new javax.swing.JLabel();
        jAccountName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jAnalyze = new javax.swing.JButton();
        jMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jVerifyBtn = new javax.swing.JButton();
        jEnrolledValue = new javax.swing.JLabel();
        jVerifyingValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jAccountNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAccountNumber.setText("jAccountNumber");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Account Number");

        jLabel3.setText("Enrolled Signature");

        jLabel4.setText("Verifying Signature");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jEnrolled, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jVerifying, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVerifying, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEnrolled, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jAccountName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAccountName.setText("jAccountName");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Account Name");

        jAnalyze.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAnalyze.setText("Analyze");
        jAnalyze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAnalyzeMouseClicked(evt);
            }
        });

        jMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu.setText("Back to Menu");
        jMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Upload Verifying Signature");

        jVerifyBtn.setText("...");
        jVerifyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVerifyBtnMouseClicked(evt);
            }
        });

        jEnrolledValue.setText("jLabel1");

        jVerifyingValue.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEnrolledValue)
                            .addComponent(jVerifyingValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAccountName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jAccountNumber)
                                        .addGap(149, 149, 149)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jVerifyBtn)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAnalyze, jMenu});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAccountNumber)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jVerifyBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAccountName)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jEnrolledValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jVerifyingValue)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jAnalyze, jMenu});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMouseClicked
                Menu mMenu = new Menu();
                Utility.centreOnScreen(mMenu);
                mMenu.setVisible(true);
                dispose();
    }//GEN-LAST:event_jMenuMouseClicked

    private void jVerifyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVerifyBtnMouseClicked
            String url;
            JFileChooser choose = new JFileChooser();
            int option = choose.showSaveDialog(this);
            if (option == JFileChooser.APPROVE_OPTION) {
            url = choose.getSelectedFile().getAbsolutePath();
            ImageIcon mImageIcon = scaleImage(url, 300, 200);
            jVerifying.setIcon(mImageIcon);
            jVerifyingValue.setText(url);
            jAnalyze.setEnabled(true);
        }
    }//GEN-LAST:event_jVerifyBtnMouseClicked

    private void jAnalyzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAnalyzeMouseClicked
    try {
            Compare mCompare = new Compare(jEnrolledValue.getText(), jVerifyingValue.getText());
            
            if(mCompare.isDone() == true && mCompare.isSame() == true){
                JOptionPane.showMessageDialog(this, "Signature Match", "Offline Signature Verification", HEIGHT);
            }
            else if(mCompare.isDone() == true && mCompare.isSame() != true){
                JOptionPane.showMessageDialog(this, "Signature does not match", "Offline Signature Verification", HEIGHT);
            }
    
        } catch (Exception ex) {
            Logger.getLogger(Verification.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jAnalyzeMouseClicked

    
        private ImageIcon scaleImage(String imagePath, int width, int height) {
        ImageIcon imageIcon = new ImageIcon(imagePath); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  // transform it back
        return imageIcon;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAccountName;
    private javax.swing.JLabel jAccountNumber;
    private javax.swing.JButton jAnalyze;
    private javax.swing.JLabel jEnrolled;
    private javax.swing.JLabel jEnrolledValue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jVerifyBtn;
    private javax.swing.JLabel jVerifying;
    private javax.swing.JLabel jVerifyingValue;
    // End of variables declaration//GEN-END:variables

    void load(ArrayList<Accounts> mResult) throws IOException, ClassNotFoundException {
        jAccountNumber.setText(mResult.get(0).getAcct_num());
        jAccountName.setText(mResult.get(0).getFullname());
        ImageIcon mImageIcon = scaleImage(mResult.get(0).getSignature(), 300, 200);
        jEnrolled.setIcon(mImageIcon);
        jEnrolledValue.setText(mResult.get(0).getSignature());
    }
}
